config:
  target: 'https://isscofunctionapp.azurewebsites.net/api'
  plugins:
    expect: {}
  phases:
    - duration: 30
      arrivalRate:  400
      name: "http function load testing"
scenarios:
  - flow:
    - get:
        url: "/HttpTriggerCSharp?code=L1yUV/B6/n2i5F1P4gQ7Or2Kv7CMvisdU3xVe8jLYSUu7vAsx9Tspg=="
        expect:
            - statusCode: 200